"""
Layer 3 - Output: Generate Architecture Decision Records as standalone files.

Renders one Markdown file per ADR following the MADR-inspired template
("Status / Context / Decision / Consequences / Alternatives") plus an index
README.md, all under <output>/<project>_adr/. The format is intentionally
compatible with adr-tools / Log4Brains so the files can be checked into
docs/adr/ of any repo without further conversion.
"""

import re
from dataclasses import dataclass
from pathlib import Path

from ..analysis.analyzer import AnalysisResult


@dataclass
class ADRGenerator:
    output_dir: str = "./output"
    language: str = "pt"

    def generate(self, result: AnalysisResult) -> list[str]:
        """Render every ADR as its own .md file plus an index README.

        Returns the list of generated file paths (index first). When the analysis
        produced no ADRs, returns an empty list and writes nothing.
        """
        adrs = getattr(result, "adrs", None) or []
        if not adrs:
            return []

        adr_dir = Path(self.output_dir) / f"{self._safe_name(result.project_name)}_adr"
        adr_dir.mkdir(parents=True, exist_ok=True)

        files: list[str] = []
        index_rows: list[str] = []

        for i, adr in enumerate(adrs, start=1):
            num = f"{i:04d}"
            slug = self._slug(adr.get("title") or f"adr-{num}")
            filename = f"{num}-{slug}.md"
            file_path = adr_dir / filename
            file_path.write_text(self._render_adr(adr, num), encoding="utf-8")
            files.append(str(file_path))
            index_rows.append(
                f"| {num} | [{adr.get('title', '')}]({filename}) | "
                f"{(adr.get('status') or 'accepted').capitalize()} |"
            )

        index_path = adr_dir / "README.md"
        index_path.write_text(self._render_index(result, index_rows), encoding="utf-8")
        files.insert(0, str(index_path))
        return files

    # ── Rendering ──────────────────────────────────────────────────────────

    def _render_index(self, result: AnalysisResult, rows: list[str]) -> str:
        L = self.language
        title = (
            f"# {result.project_name} - Decisoes Arquiteturais"
            if L == "pt" else
            f"# {result.project_name} - Architecture Decision Records"
        )
        intro = (
            "Conjunto de decisoes arquiteturais identificadas automaticamente pelo "
            "ArchDocAI a partir do codigo do projeto. Cada arquivo segue o formato "
            "MADR (Markdown Any Decision Record) e pode ser editado manualmente."
            if L == "pt" else
            "Architectural decisions identified automatically by ArchDocAI from the "
            "project's code. Each file follows the MADR (Markdown Any Decision Record) "
            "format and can be hand-edited."
        )
        header = "| # | Titulo | Status |" if L == "pt" else "| # | Title | Status |"
        return "\n".join([
            title, "", intro, "",
            header, "|---|---|---|",
            *rows, "",
            "---", "",
            "_Gerado por ArchDocAI_" if L == "pt" else "_Generated by ArchDocAI_",
            "",
        ])

    def _render_adr(self, adr: dict, number: str) -> str:
        L = self.language
        title = (adr.get("title") or "Untitled").strip()
        status = (adr.get("status") or "accepted").capitalize()

        if L == "pt":
            h = ("Status", "Contexto", "Decisao", "Consequencias", "Alternativas Consideradas")
            empty = "_(nao especificado)_"
            footer = "_Gerado por ArchDocAI_"
        else:
            h = ("Status", "Context", "Decision", "Consequences", "Alternatives Considered")
            empty = "_(not specified)_"
            footer = "_Generated by ArchDocAI_"

        parts: list[str] = [f"# ADR-{number}: {title}", ""]
        parts += [f"## {h[0]}", "", status, ""]
        parts += [f"## {h[1]}", "", (adr.get("context") or "").strip() or empty, ""]
        parts += [f"## {h[2]}", "", (adr.get("decision") or "").strip() or empty, ""]
        parts += [f"## {h[3]}", "", (adr.get("consequences") or "").strip() or empty, ""]
        if (adr.get("alternatives") or "").strip():
            parts += [f"## {h[4]}", "", adr["alternatives"].strip(), ""]
        parts += ["---", "", footer, ""]
        return "\n".join(parts)

    # ── Helpers ────────────────────────────────────────────────────────────

    def _slug(self, text: str) -> str:
        text = text.lower()
        text = re.sub(r"[^\w\s-]", "", text)
        text = re.sub(r"[\s_]+", "-", text).strip("-")
        return text[:60] or "adr"

    def _safe_name(self, name: str) -> str:
        return "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
